<?xml version="1.0"?>
<robot name="ackermann_car" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="chassis_length" value="0.27"/> <xacro:property name="chassis_width" value="0.12"/>  <xacro:property name="chassis_height" value="0.08"/> <xacro:property name="lidar_radius" value="0.035"/>
  <xacro:property name="lidar_height" value="0.03"/>
  
  <xacro:property name="lidar_x_offset" value="-0.07"/> 
  
  <xacro:property name="lidar_z_offset" value="${chassis_height/2 + lidar_height/2}"/>
  <xacro:property name="ground_clearance" value="0.03"/>

  <material name="blue"><color rgba="0 0 0.8 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
  </link>

  <link name="base_footprint"/>
  
  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 ${-(chassis_height/2 + ground_clearance)}" rpy="0 0 0"/>
  </joint>

  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="${lidar_x_offset} 0 ${lidar_z_offset}" rpy="0 0 0"/>
  </joint>

</robot>
